<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_Question 3</name>
   <tag></tag>
   <elementGuidId>f77f70d4-b864-4467-9dee-735048c2d249</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h5[@id='mz-faq-label-214664-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mz-faq-label-214664-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>4a5d01ba-f13b-465b-a091-10304be18816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mz-faq-label-214664-2</value>
      <webElementGuid>f36c5bce-3dd4-4d39-a7a5-ee907cdd7e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-header border-bottom-0 align-items-center d-flex collapsed</value>
      <webElementGuid>1a3dc4c1-07aa-46a0-88c2-5a9f8e82d0bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>fed373d8-1b66-4646-97c5-ccf857d621ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5decf6ea-da2e-49a7-83ba-de1279070bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>mz-faq-panel-214664-2</value>
      <webElementGuid>8f9f457f-eb68-4e08-b140-d7506fe6f5f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#mz-faq-panel-214664-2</value>
      <webElementGuid>2a52c0fb-7d6c-498f-a3de-97f6516a92fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Question 3  </value>
      <webElementGuid>7dedf6af-617f-4d27-aa69-00ed8f66dfe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mz-faq-label-214664-2&quot;)</value>
      <webElementGuid>b628f255-b078-4684-b21c-fbcc7fd2bd2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h5[@id='mz-faq-label-214664-2']</value>
      <webElementGuid>e491ee55-ec37-4453-b96f-47f4082c2520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mz-widget-faq-214664']/div[3]/div/h5</value>
      <webElementGuid>db9044dd-abf0-4c1f-bd84-6df2a3f5f5a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Question 2'])[1]/following::h5[1]</value>
      <webElementGuid>1db8553a-aea4-4453-b4ad-0190a939f13c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Question 1'])[1]/following::h5[2]</value>
      <webElementGuid>97022608-1596-413f-9a95-b6ac0449193f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category'])[1]/preceding::h5[1]</value>
      <webElementGuid>0b331d71-f345-446a-a208-1a680e39ad56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/h5</value>
      <webElementGuid>526ca359-5c3c-45d9-a0c6-476499d9e921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[@id = 'mz-faq-label-214664-2' and (text() = ' Question 3  ' or . = ' Question 3  ')]</value>
      <webElementGuid>956691ea-64bd-48ad-9601-1a7e48298ad1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
