<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_Question 1</name>
   <tag></tag>
   <elementGuidId>92ed7546-e40a-428f-8f78-28e01687c290</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h5[@id='mz-faq-label-214664-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mz-faq-label-214664-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>e4411b98-3ca6-4633-923b-b4fa0f8ccadb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mz-faq-label-214664-0</value>
      <webElementGuid>03125fb0-2a09-41b7-b127-95754f7226a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-header border-bottom-0 align-items-center d-flex collapsed</value>
      <webElementGuid>b83c2aee-1423-4019-afc0-aadb432f8c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>37079591-ae2f-4651-83e0-3324b471d09d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8f253a85-e3a9-45d5-a770-5fe6c207123a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>mz-faq-panel-214664-0</value>
      <webElementGuid>265dc885-1df7-447d-9ed8-816bd6efdce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#mz-faq-panel-214664-0</value>
      <webElementGuid>de54d0ed-c0c0-45cb-9d30-392fbe1f0566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Question 1  </value>
      <webElementGuid>294c524f-ed43-45bf-b5a7-8130e98d857e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mz-faq-label-214664-0&quot;)</value>
      <webElementGuid>38cec5dd-e70a-4968-b9d2-c0e6d48b74b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h5[@id='mz-faq-label-214664-0']</value>
      <webElementGuid>ea210d35-98fa-48ba-ac7c-8f3e0ebffcd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mz-widget-faq-214664']/div/div/h5</value>
      <webElementGuid>35ec95e7-74a7-405b-8125-166614ce82e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQ'])[1]/following::h5[1]</value>
      <webElementGuid>0d490c2c-82af-4ce0-a260-3568610ec392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Up to Effect 12'])[1]/following::h5[1]</value>
      <webElementGuid>2d64b146-754f-41a0-9140-4f0085b1e9f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Question 2'])[1]/preceding::h5[1]</value>
      <webElementGuid>52271cc0-7fae-4ae8-8d84-9bce46dcaf70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/h5</value>
      <webElementGuid>e431fcaf-2012-496b-91dd-6269d275189d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[@id = 'mz-faq-label-214664-0' and (text() = ' Question 1  ' or . = ' Question 1  ')]</value>
      <webElementGuid>0417020b-0569-42dc-9987-df8e11b119ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
