<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_Question 2</name>
   <tag></tag>
   <elementGuidId>38fb527f-be54-4499-ba71-2a4ebc242717</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h5[@id='mz-faq-label-214664-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mz-faq-label-214664-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>cafcdb18-4f45-4565-9f42-c72522bea0a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mz-faq-label-214664-1</value>
      <webElementGuid>e9188735-654e-4182-a888-ef0d4489393b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-header border-bottom-0 align-items-center d-flex collapsed</value>
      <webElementGuid>1913d324-87c8-47ef-b704-2e2d5f75771b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>60c94f2e-ba90-4b50-bfbf-fc656256dd24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6dd4dd80-5e63-4750-b0dc-60d4ba247570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>mz-faq-panel-214664-1</value>
      <webElementGuid>465c2aff-4291-48b7-b1d6-7b03d718f4b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#mz-faq-panel-214664-1</value>
      <webElementGuid>ff81bdf6-7434-4db8-a60b-d0a6fc8806e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Question 2  </value>
      <webElementGuid>81a6138c-6120-4997-aaff-63d7d3216209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mz-faq-label-214664-1&quot;)</value>
      <webElementGuid>569e3d3b-7f13-4fd7-af6b-5a9155d000b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h5[@id='mz-faq-label-214664-1']</value>
      <webElementGuid>fe23cccd-c970-4ff9-a565-27ab780e051f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mz-widget-faq-214664']/div[2]/div/h5</value>
      <webElementGuid>3dc364c1-f37f-4164-84d3-a5787582d5ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Question 1'])[1]/following::h5[1]</value>
      <webElementGuid>a5a40ad9-950d-43d9-8fd8-c5bfc85aa758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQ'])[1]/following::h5[2]</value>
      <webElementGuid>7471b1b6-0e22-4d6f-ab6b-4351f39e47ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Question 3'])[1]/preceding::h5[1]</value>
      <webElementGuid>e1c1fe40-8f5b-413a-be13-e52aa6717453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h5</value>
      <webElementGuid>c625bdbb-f50c-4b4d-82ef-cb22c1b4cce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[@id = 'mz-faq-label-214664-1' and (text() = ' Question 2  ' or . = ' Question 2  ')]</value>
      <webElementGuid>9ea87ecd-03f7-430b-8e7f-7a7848c23522</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
