<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Account Name_bank_account_name</name>
   <tag></tag>
   <elementGuidId>244e1929-e8a1-4606-9bc4-265d81dac2ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-bank-account-name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-bank-account-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7158edf8-acb9-43a8-9cf1-5753e0c6380e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>85a7a403-a0c4-485c-b6b6-b5da086b337f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bank_account_name</value>
      <webElementGuid>3ac347e7-c3af-4a0c-8be7-7789f7c346a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Account Name</value>
      <webElementGuid>c99367ce-883c-439d-b707-da713ab6a961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-bank-account-name</value>
      <webElementGuid>82ea0481-8da7-4f27-b791-09425fc7b22c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bcb86f35-e2f3-45c7-a591-cd77f280c7f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-bank-account-name&quot;)</value>
      <webElementGuid>bf49e7cd-fee6-4004-89bb-7487bc0da6fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-bank-account-name']</value>
      <webElementGuid>f19d6d69-247f-4b58-b2e2-ae9469c10f18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-bank']/div[4]/div/input</value>
      <webElementGuid>f6c6f671-c6da-43ff-aed9-3c6c859b2bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[4]/div/input</value>
      <webElementGuid>dd1fc064-804d-4235-a77d-3570ca08a0b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'bank_account_name' and @placeholder = 'Account Name' and @id = 'input-bank-account-name']</value>
      <webElementGuid>0373aa99-ec8d-4a34-853e-f142fac77b0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
