<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ABABSB number (Branch Number)_bank_br_618171</name>
   <tag></tag>
   <elementGuidId>53f4a5f0-916b-46e3-a84a-20d5e26d8881</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-bank-branch-number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-bank-branch-number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6cac384e-2e6c-40dd-ad87-50b2511972d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>08ea1a21-9411-48e6-a3bb-51ff95cd6355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bank_branch_number</value>
      <webElementGuid>ba3b3cb9-24fc-4ffe-9b10-15194237ced0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ABA/BSB number (Branch Number)</value>
      <webElementGuid>f1fe3cd8-0dd7-4e0c-944f-dc4dc67337a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-bank-branch-number</value>
      <webElementGuid>34b82018-e63d-4ceb-9d02-ac0aa2312c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4aaac41f-25df-4b40-9981-2fb3fbe467b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-bank-branch-number&quot;)</value>
      <webElementGuid>14178836-0cd3-4082-85c1-e3353c08f6e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-bank-branch-number']</value>
      <webElementGuid>8e48aef5-43ed-45a3-a527-03ee9abd9f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-bank']/div[2]/div/input</value>
      <webElementGuid>a5d7b639-3078-4d0f-99dd-48058082da23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/input</value>
      <webElementGuid>cb2338d0-2a89-4df7-b197-627208c1d954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'bank_branch_number' and @placeholder = 'ABA/BSB number (Branch Number)' and @id = 'input-bank-branch-number']</value>
      <webElementGuid>992ab4f8-8f1d-4ec6-abc9-f4e3480ea537</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
