<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bank Transfer_payment</name>
   <tag></tag>
   <elementGuidId>e2e8b864-3930-4fda-8e57-956129328bf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='payment'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60fbcba6-88ac-4f07-9080-eb2713ac53f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>eb74657b-2a8c-4e47-bd8a-6c5223a2f3d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment</value>
      <webElementGuid>2f924b94-878f-46ea-ba6e-f38c10c14523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>bank</value>
      <webElementGuid>e3ef2fd6-468a-4e84-a625-0cd00918b8f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>00e18c7d-05cc-4423-bb92-ea1d2a6df246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/form[@class=&quot;mb-4&quot;]/fieldset[2]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-sm-10&quot;]/div[@class=&quot;form-check&quot;]/label[1]/input[@class=&quot;form-check-input&quot;]</value>
      <webElementGuid>238807b5-c26f-4ddb-8fff-a6c4c3d71213</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='payment'])[3]</value>
      <webElementGuid>84494462-f3fb-450f-aa12-c2db2f6dcc1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/form/fieldset[2]/div[2]/div/div[3]/label/input</value>
      <webElementGuid>259b34df-f691-4320-bb6f-34fc53be8ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/input</value>
      <webElementGuid>afba6578-a3b8-481f-a419-174250c64ca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'payment']</value>
      <webElementGuid>f200cbb8-9e8a-494b-beff-a734d02b43a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
