<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Add to Cart_fas fa-heart_1</name>
   <tag></tag>
   <elementGuidId>761c7caa-3137-4a56-87ec-8ff096048d31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='entry_212408']/div/div[5]/div/div/div[2]/button[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>0125752d-1890-4f21-a3a9-39dd82b86f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-heart</value>
      <webElementGuid>bbb6d90e-3bbb-4bd1-b49d-3910ebeffde8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;entry_212408&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;product-layout product-grid no-desc col-xl-4 col-lg-4 col-md-4 col-sm-6 col-6&quot;]/div[@class=&quot;product-thumb&quot;]/div[@class=&quot;product-thumb-top&quot;]/div[@class=&quot;product-action&quot;]/button[@class=&quot;btn btn-wishlist wishlist-32&quot;]/i[@class=&quot;fas fa-heart&quot;]</value>
      <webElementGuid>db6f04f5-9221-448e-a7d3-ade931dcfade</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='entry_212408']/div/div[5]/div/div/div[2]/button[2]/i</value>
      <webElementGuid>e57fce13-054e-44f0-aa36-b23d85ad995e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/button[2]/i</value>
      <webElementGuid>25b7f958-29cf-4a06-8c48-a9232da937d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
