<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Register for an affiliate account</name>
   <tag></tag>
   <elementGuidId>5c1a3287-9285-4e36-a593-5608305eede6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.card-body.text-center.text-sm-left</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8410e064-4a29-45de-820b-d1dbd09b596d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-body text-center text-sm-left</value>
      <webElementGuid>59cc305f-774e-4d9b-b25a-567e2b4433c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Register for an affiliate account </value>
      <webElementGuid>c3f6495a-525f-4ae7-a2dc-8be132535f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;card mb-3&quot;]/div[@class=&quot;card-body text-center text-sm-left&quot;]</value>
      <webElementGuid>e47d785e-3aac-4f5c-ae63-cf8e594f20e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[3]/div</value>
      <webElementGuid>648b29f1-5bcb-43e0-b94b-5963730b6d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Affiliate Account'])[1]/following::div[1]</value>
      <webElementGuid>052f977d-c46e-4518-92be-bb7b73efabd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recurring payments'])[1]/following::div[2]</value>
      <webElementGuid>cc6f9a58-c779-4cb6-a301-1bb78f48a112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Account'])[3]/preceding::div[1]</value>
      <webElementGuid>cfa6e85f-a03c-4770-8dea-9432f9069ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div[3]/div</value>
      <webElementGuid>bd431708-9f13-4753-890f-25507e5a1e1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '  Register for an affiliate account ' or . = '  Register for an affiliate account ')]</value>
      <webElementGuid>4841ccaf-322e-4614-ace2-78e882351c18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
