<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Checkout_figure-img img-fluid m-0 default</name>
   <tag></tag>
   <elementGuidId>9e68a0e4-52e3-4873-b659-cb81e9951468</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='entry_217821']/figure/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.figure-img.img-fluid.m-0.default</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6d83ee48-7f40-44cf-8cb5-8356e5792d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ecommerce-playground.lambdatest.io/image/catalog/maza/svg/image2vector.svg</value>
      <webElementGuid>19268f4b-5f67-409f-aacc-4f8e40fc9a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Poco Electro</value>
      <webElementGuid>f3df801a-37c0-4b3d-9dd2-de38648fe8d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>151</value>
      <webElementGuid>8b67ad4d-7776-49ef-9042-778b4f00cc0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>5a80fa83-8e12-4ddc-aefa-06b40987c06f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>figure-img img-fluid m-0 default</value>
      <webElementGuid>fcc3cc5b-10c4-494d-83e2-6307f1564a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;entry_217821&quot;)/figure[@class=&quot;figure&quot;]/a[1]/img[@class=&quot;figure-img img-fluid m-0 default&quot;]</value>
      <webElementGuid>14d4c7ad-d0b6-4f72-a98a-db4f641d0114</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='entry_217821']/figure/a/img</value>
      <webElementGuid>e4c8adc9-1f53-486c-912e-c93b384ec619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Poco Electro']</value>
      <webElementGuid>eaa0d127-9f9c-48c3-90f1-f01b33fca19d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/a/img</value>
      <webElementGuid>c636118b-49a9-46b6-a5de-f0a02c1e29a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ecommerce-playground.lambdatest.io/image/catalog/maza/svg/image2vector.svg' and @alt = 'Poco Electro']</value>
      <webElementGuid>3e1cab38-2dc8-4b24-b26e-8d926a8dd97d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
