<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Price_mz_fpmin</name>
   <tag></tag>
   <elementGuidId>cb929616-65c9-4f1f-a76e-4753a1b95a27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='mz_fp[min]'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mz-filter-panel-0-0 > div.mz-filter-group-content > div.d-flex.align-items-center > input[name=&quot;mz_fp[min]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dcdae030-bb56-4b6c-97b2-b54f81a336a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>4883dd2f-106b-4b29-936e-dda6aff24910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mz_fp[min]</value>
      <webElementGuid>15c6427b-bac1-450f-a8a6-608fd9dda09e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d734a433-6b6c-424f-8278-019c55004712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>98</value>
      <webElementGuid>ce6fd2c0-5ce1-4aaa-a7c7-d7cdb0c11a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>98</value>
      <webElementGuid>37d33b47-aee7-44f2-95c3-fa7124f08619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>1999</value>
      <webElementGuid>b88f0ecf-b034-468b-a69c-937aabb207ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Minimum Price</value>
      <webElementGuid>fbb41dd8-bc2b-4d07-9c03-917b582ee271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Minimum Price</value>
      <webElementGuid>5c08aea5-3575-4d16-8ec5-2ef6f0ab6057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mz-filter-panel-0-0&quot;)/div[@class=&quot;mz-filter-group-content&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>966c4949-a29d-418c-8446-613d10d93e13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='mz_fp[min]'])[2]</value>
      <webElementGuid>71799778-08d0-46fb-8604-37a6be50e996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mz-filter-panel-0-0']/div/div[2]/input</value>
      <webElementGuid>e04bc427-b8eb-4a99-8c2b-47d3ba6c90d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/input</value>
      <webElementGuid>9b894f16-9c3d-40ca-8246-a4d370ca0893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'mz_fp[min]' and @placeholder = 'Minimum Price']</value>
      <webElementGuid>1974467c-f5f9-4bf5-b140-ec57ca73835f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
